const crypto = require('crypto');

const makeId = () => crypto.randomUUID();

const organizations = [
  {
    _id: makeId(),
    name: 'Saathi New Delhi NGO',
    slug: 'saathi-new-delhi',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    address: 'Connaught Place, New Delhi, Delhi',
    location: { type: 'Point', coordinates: [77.2167, 28.6139], address: 'Connaught Place, New Delhi, Delhi' },
    radiusKm: 25,
    active: true,
  },
  {
    _id: makeId(),
    name: 'Saathi Mumbai NGO',
    slug: 'saathi-mumbai',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    address: 'Fort, Mumbai, Maharashtra',
    location: { type: 'Point', coordinates: [72.8777, 19.076], address: 'Fort, Mumbai, Maharashtra' },
    radiusKm: 25,
    active: true,
  },
  {
    _id: makeId(),
    name: 'Saathi Patna NGO',
    slug: 'saathi-patna',
    city: 'Patna',
    state: 'Bihar',
    country: 'India',
    address: 'Danapur, Patna, Bihar',
    location: { type: 'Point', coordinates: [85.1376, 25.5941], address: 'Danapur, Patna, Bihar' },
    radiusKm: 25,
    active: true,
  },
];

const volunteers = [
  {
    name: 'Rahul Delhi',
    phone: '9876500001',
    email: 'rahul.delhi@saathi.com',
    organization: organizations[0]._id,
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    role: 'ngo_worker',
    skills: ['Construction', 'Logistics'],
    availability: { days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], times: ['Morning'] },
    location: { type: 'Point', coordinates: [77.209, 28.6139], address: 'New Delhi, Delhi' },
  },
  {
    name: 'Priya Delhi',
    phone: '9876500002',
    email: 'priya.delhi@saathi.com',
    organization: organizations[0]._id,
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    role: 'ngo_worker',
    skills: ['Medical', 'Counseling'],
    availability: { days: ['Monday', 'Wednesday', 'Friday'], times: ['Morning', 'Afternoon'] },
    location: { type: 'Point', coordinates: [77.1025, 28.7041], address: 'New Delhi, Delhi' },
  },
  {
    name: 'Amit Mumbai',
    phone: '9876500003',
    email: 'amit.mumbai@saathi.com',
    organization: organizations[1]._id,
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    role: 'ngo_worker',
    skills: ['Food Distribution', 'Education'],
    availability: { days: ['Tuesday', 'Thursday', 'Saturday'], times: ['Morning'] },
    location: { type: 'Point', coordinates: [72.88, 19.08], address: 'Mumbai, Maharashtra' },
  },
];

const citizens = [
  {
    name: 'Citizen Delhi',
    phone: '9000000001',
    email: 'citizen.delhi@example.com',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    preferredOrganization: organizations[0]._id,
    location: { type: 'Point', coordinates: [77.215, 28.62], address: 'New Delhi, Delhi' },
  },
  {
    name: 'Citizen Mumbai',
    phone: '9000000002',
    email: 'citizen.mumbai@example.com',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    preferredOrganization: organizations[1]._id,
    location: { type: 'Point', coordinates: [72.86, 19.09], address: 'Mumbai, Maharashtra' },
  },
];

const reports = [
  {
    organization: organizations[0]._id,
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    citizen: citizens[0]._id,
    reporterName: 'Citizen Delhi',
    reporterPhone: '9000000001',
    issueType: 'Health',
    urgency: 9,
    description: 'Medicine shortage in New Delhi neighborhood',
    location: { type: 'Point', coordinates: [77.213, 28.618], address: 'Connaught Place, New Delhi, Delhi' },
    status: 'Pending',
  },
  {
    organization: organizations[0]._id,
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    citizen: citizens[0]._id,
    reporterName: 'Citizen Delhi',
    reporterPhone: '9000000001',
    issueType: 'Infrastructure',
    urgency: 8,
    description: 'Waterlogging near market road in New Delhi',
    location: { type: 'Point', coordinates: [77.208, 28.615], address: 'Connaught Place, New Delhi, Delhi' },
    status: 'Pending',
  },
  {
    organization: organizations[1]._id,
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    citizen: citizens[1]._id,
    reporterName: 'Citizen Mumbai',
    reporterPhone: '9000000002',
    issueType: 'Food',
    urgency: 9,
    description: 'Food shortage in Mumbai local area',
    location: { type: 'Point', coordinates: [72.875, 19.08], address: 'Fort, Mumbai, Maharashtra' },
    status: 'Pending',
  },
];

module.exports = { organizations, volunteers, citizens, reports };
